### ISSUE TITLE
1.18 when?

### ISSUE THREAD

**Issue by QwertyTheCoder** [PacketDeveloper/PacketClient#5]

**Comment by MrDiamond64** [comment]
hii guys i love packe4t client iz my favorite packet4life guyz!! i hate my own anticheat it cant detect shit LOL!!!!!

**Comment by PacketDeveloper** [comment]
wow thanks!!!

**Comment by MrDiamond64** [comment]
> wow thanks!!!

you are very welcome 😊

**Comment by PacketDeveloper** [comment]
1.18 will come out sometime soon

**Comment by MrDiamond64** [comment]
> 1.18 will come out sometime soon

"I wonder how much money you paid onix." is what i would've said, but to stop myself from being humiliated i decided not too, you have come a very long way thx for making my favz client !!111
